name: DA Build Workflow

on: push


jobs:

  buildDaJob:

    name: Build DA job
    runs-on: ubuntu-20.04
    container: ghcr.io/ingokofler/pandoc4all:latest

    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@v2
        with:
          path: da_repo
      - run: ls -la
      - run: cd ..
      - run: ls -la
