name: DA Build Workflow new

on: push

env:
  OUTPUTDIR: output
  STYLEDIR: style
  INPUTDIR: sources

jobs:

  buildDaJob:

    name: Build DA job
    runs-on: ubuntu-20.04
    container: ghcr.io/ingokofler/pandoc4all:feat-support-da-template

    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@v2
        with:
          path: da_repo
      - run: ls -la
      - run: |
          pandoc \
          --output "$OUTPUTDIR/diplomarbeit.tex" \
          --template="$STYLEDIR/htl-da/Pandoc_DA.tex" \
          "$INPUTDIR/metadata.yml" \
          "$INPUTDIR"/*.md \
          --verbose \
          --biblatex \
          --top-level-division=chapter \
          --listings \
          2>htl-latex.log
      - name: Upload Log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: make_log
          path: htl-latex.log