name: DA Build Workflow new

on: push

env:
  OUTPUTDIR: output
  STYLEDIR: style
  INPUTDIR: source

jobs:

  buildDaJob:

    name: Build DA job
    runs-on: ubuntu-20.04
    container: ghcr.io/ingokofler/pandoc4all:feat-support-da-template

    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@v2
        with:
          path: da_repo
      - run: ls -la
      - run: mkdir -p output
        working-directory: da_repo
      - run: |
          pandoc \
          --output "$OUTPUTDIR/diplomarbeit.tex" \
          --template="$STYLEDIR/htl-da/Pandoc_DA.tex" \
          "$INPUTDIR/metadata.yml" \
          "$INPUTDIR"/*.md \
          --verbose \
          --biblatex \
          --top-level-division=chapter \
          --listings \
          2>htl-latex.log
        working-directory: da_repo
      - run: mkdir -p source
        working-directory: da_repo/output
      - run: cp -rf ../source/figures source
        working-directory: da_repo/output
      - run: cp -rf ../source/references.bib .
        working-directory: da_repo/output
      - run: cp -rf ../style/htl-da/chapters ../style/htl-da/includes ../style/htl-da/media .
        working-directory: da_repo/output
      - run: pdflatex diplomarbeit.tex
        working-directory: da_repo/output
      - run: bibtex diplomarbeit
        working-directory: da_repo/output
      - run: pdflatex diplomarbeit.tex
        working-directory: da_repo/output
      - run: pdflatex diplomarbeit.tex
        working-directory: da_repo/output

      - name: Upload Log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: make_log
          path: da_repo/output/diplomarbeit.tex